spring:
  application:
    name: cms-admin
  datasource:
    druid:
      url: jdbc:mysql://${db.server}:${db.port}/db_cms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: ${db.user}
      password: ${db.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
#      配置获取连接等待超时时间
      max-wait: 60000
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true
      filters: stat
  jackson:
    date-format: yyyy-MM-dd hh:mm
  thymeleaf:
    cache: false
#    配置文件上传大小
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
#  http:
#    multipart:
#      max-file-size: 3MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.gangster.cms.common.pojo
#management:
#  security:
#    enabled: false
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://${eureka_server}:${eureka_port}/eureka/
    fetch-registry: true
eureka_server: localhost
eureka_port: 8761
server:
  port: 8080
db:
  server: db_server
  port: 3306
  user: root
  password: "$%^YGR^&UHGT^&U"
pagehelper:
  reasonable: true

#feign:
#  hystrix:
#    enabled: true
#cms:
#  common:  可配置超级管理员的名称
#    admi:
#      name: