spring:
  datasource:
    druid:
      url: jdbc:mysql://${db.server}:${db.port}/db_cms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: ${db.user}
      password: ${db.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.gangster.cms.common.pojo
pagehelper:
  reasonable: true
server:
  port: 8090
logging:
  level:
    root: info
db:
  server: db_server
  port: 3306
  user: root
  password: "$%^YGR^&UHGT^&U"

#  for search
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://${eureka_server}:${eureka_port}/eureka/
    fetch-registry: true
eureka_server: localhost
eureka_port: 8761
server:
  port: 8080