spring:
  datasource:
    druid:
      url: jdbc:mysql://db_server:3306/db_cms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: "$%^YGR^&UHGT^&U"
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.ganster.cms.core.pojo
pagehelper:
  reasonable: true
server:
  port: 8090
logging:
  level:
    root: info